name: Deploy to Beanstalk

on:
  push:
    branches:
      - dev
      - cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.16.0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Make a zip file
        run: zip -r deploy.zip . -x "node_modules/*" "coverage/*" "src/*" "test/*" "README.md" "*.git*"
        shell: bash


      - name: Deploy to Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-northeast-2
          application_name: heet-server,
          environment_name: Heetserver-env
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

      - name: Clean up
        run: rm -rf node_modules/ dist/
